[package]
name = "literate-octo-tribble"
version = "0.1.0"
authors = ["SilanSurfer <szwarc.adam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
